eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8762/eureka}
okta:
  oauth2:
    issuer: https://dev-74942036.okta.com/oauth2/default
    audience: api://default
